apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" $ }}-init-sql
  labels:
    {{- include "postgres.labels" $ | nindent 4 }}
    app.kubernetes.io/component: db
data:
 
  {{- (.Files.Glob "files/init2.sql").AsConfig | nindent 2 }}
